import asyncio
import main

SYN_ROWS = [
    {
        'CONTRACT_CODE': 'SYN1', 'DISTRICTNAME': 'KIRKOS', 'CBE_REGION': 'ADDIS ABABA', 'BRANCHNAME': 'MAIN',
        'APPROVED_AMOUNT': 10000, 'TENURE': 'SHORT', 'TERM': 'MONTHLY', 'LOAN_TYPE': 'TYPE1',
        'LOAN_DESCRIPTION': 'DESC', 'LOAN_PRODUCT': 'PROD', 'LTYPE': 'L', 'PRINCIPAL_OS': 5000,
        'INTEREST_OS': 100, 'PRINCIPAL_ARREARS': 0, 'CURRENT_COMMITTMENT': 200, 'INSTALLMENT_AMOUNT': 300,
        'ECONOMIC_SECTOR': 'AGR', 'INDUSTRY': 'IND', 'OWNERSHIP': 'PRIVATE', 'SECTOR': 'SOME',
        'TERM_OF_PAYMENT': 'MONTHLY', 'PRODUCT_OWNER': 'OWNER', 'COLLATERAL_VALUE': 2000,
        'GRANT_DATE': '2024-01-01', 'EXPIRY_DATE': '2026-01-01', 'BUSINESS_DATE': '2026-05-07'
    },
    {
        'CONTRACT_CODE': 'SYN2', 'DISTRICTNAME': 'MERKATO', 'CBE_REGION': 'ADDIS ABABA', 'BRANCHNAME': 'EAST',
        'APPROVED_AMOUNT': 50000, 'TENURE': 'LONG', 'TERM': 'MONTHLY', 'LOAN_TYPE': 'TYPE2',
        'LOAN_DESCRIPTION': 'DESC2', 'LOAN_PRODUCT': 'PROD2', 'LTYPE': 'M', 'PRINCIPAL_OS': 20000,
        'INTEREST_OS': 500, 'PRINCIPAL_ARREARS': 100, 'CURRENT_COMMITTMENT': 1000, 'INSTALLMENT_AMOUNT': 2000,
        'ECONOMIC_SECTOR': 'SERV', 'INDUSTRY': 'SERVIND', 'OWNERSHIP': 'GOV', 'SECTOR': 'OTHER',
        'TERM_OF_PAYMENT': 'QUARTERLY', 'PRODUCT_OWNER': 'OWNER2', 'COLLATERAL_VALUE': 10000,
        'GRANT_DATE': '2023-01-01', 'EXPIRY_DATE': '2028-01-01', 'BUSINESS_DATE': '2026-05-07'
    },
    {
        'CONTRACT_CODE': 'SYN3', 'DISTRICTNAME': 'HAWASSA', 'CBE_REGION': 'SIDAMA', 'BRANCHNAME': 'SOUTH',
        'APPROVED_AMOUNT': 25000, 'TENURE': 'MEDIUM', 'TERM': 'MONTHLY', 'LOAN_TYPE': 'TYPE3',
        'LOAN_DESCRIPTION': 'DESC3', 'LOAN_PRODUCT': 'PROD3', 'LTYPE': 'S', 'PRINCIPAL_OS': 12000,
        'INTEREST_OS': 250, 'PRINCIPAL_ARREARS': 50, 'CURRENT_COMMITTMENT': 500, 'INSTALLMENT_AMOUNT': 800,
        'ECONOMIC_SECTOR': 'IND', 'INDUSTRY': 'MAN', 'OWNERSHIP': 'PRIVATE', 'SECTOR': 'MANUF',
        'TERM_OF_PAYMENT': 'MONTHLY', 'PRODUCT_OWNER': 'OWNER3', 'COLLATERAL_VALUE': 5000,
        'GRANT_DATE': '2022-06-01', 'EXPIRY_DATE': '2025-06-01', 'BUSINESS_DATE': '2026-05-07'
    }
]

async def run():
    print('Using CLASS_THRESHOLDS =', getattr(main, 'CLASS_THRESHOLDS', None))
    for r in SYN_ROWS:
        res = await main.predict(**r)
        print(f"{r['CONTRACT_CODE']} -> prediction={res['prediction']} SME={res['sme_probability']} NPL={res['npl_probability']} all={res['all_probabilities']}")

if __name__ == '__main__':
    asyncio.run(run())
